# Generated by Django 3.0.6 on 2020-05-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmovies', '0003_auto_20200527_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='descript',
            field=models.TextField(default=''),
        ),
    ]
